include("test_mapping.jl")
include("test_graph.jl")
include("test_system.jl")
include("test_abstraction.jl")
include("test_symbolic_model.jl")
include("test_viable_states.jl")
include("test_viable_states_symbolic_model.jl")
